sudo: false
env:
  global:
    # Doctr token
    - secure: "CE68N8pVwz8X3Ot0KPXtUg8y5oPbJpwkaNyq1nyFKcdhYKoT0EFE5KjaSaNYgYgHojMpQvdhSLtdBpbDoqqDjwyw1N06rndZpVhxhoq8BDmFLs02pN/+w7ihKH73w5aYAqFVCNAF0WW9nLFn2Sg+948V9XlSe4XxH9a1paw8C9wGLF4XbyObGLV4ej1oxv7XDx4//ehOBZDjuVdfZYRZ65HFb+AIQD9OUlZ6aEHczNyQ8sAQxwTdRayWbRY+kjB8Oaa8chtEa/sfQLGnAMQTuxomTD5D40B2AiMbt53BWT2rDgih5Y8padpIGiDgCSQL+XtGlPsRLv/Wr3k9oRpJ1fwGEdBHC4Zn+J6nIy7xGPFEbvCOMbYI0Ie34bqEYZfu+E6bVwbLqMDKo+sZ+mMkrwCPVMKQoWMyx8cYuP0oMKlyAYYYK0V9YGjqgszmLaIDogP/aUMPBN9s92P4VURlhpDuFvAeGpEGT1cb/8deWShMXvx2NCvDsjRCYFZ73qcPxkA1VI03T25gjOBvbnreKltuu17Mteq1i7Gk/ULDvJNGMYrd/2ap/wiAXjFM3sGSDN5LKMCqQNHbzx438Q0Wu12TT85g9bDWAlMMawKxXRCFasbHZJmTJ9vC2c1xtbRyhPf6eiP4RG1EiPX0Y3DpZq9neUfX7wvtd4VL3gZOhBo="
    # Anaconda token
    - secure: "hQ1JZpQ5T4JQSsCF6ynqUzJPT16ahh1g72nRtJFrqSRxBBkO4LLi+GQuCrLrz3hvKMFUIFXTrxYn8qRo+GvL0WPbz3zFCi+su0p6xpv5yaPiQMQMtzkgPlwM8nYHEufmyng6NchN3D+LWcLO56mrQyjEFGecTjB4OApW0/1goOGLjNIlnpV0VKFQt9+iweHL2adL7Xo21UwCN5RbSRnfQ2SYDglynyKCY7S6JNhy8nYCVu8DelVjE0VTCfzPkFRDgPiqYP2L/c2zgLZ8ZBIbRnkAESLd373zkbZDQ1twnmOor6qOQh9ZdR9OlYOatSQhrkEe9HMnweGFUzC6DMv7AL3aVcQ6tvzMRVCFiBVaLiIbvU8ZJDUocTvqZbBKb49pB3O8tCG7FT24O4VLBaTg/dSHfVHX+IX2g8ucG8SLtv07f0DBTxdo69l1tkuzTdibncaeFWis79MS02yNfTeaqBdTVerehvkOUVKl1NqVshwCwFQILZvKKNsHsHBWk0AkEH/XPt2isvvfDYTaQl3RuBeyrloY//oB3IH8CGPnaF+xRPpsj2CQEwKPL81AC5VcZmFcwcM56+VC2X6fmcJXi/19kTOYw3KULboGnr9SJd+FPCsRjkPqsaN/KS4eEm+4BE2icgHRlPjMREFMJjzFKyrFgT4YgwiyPphio3DDu4k="

language: generic

matrix:
  include:
    - os: linux
      env: PYTHON="3.5"

    - os: linux
      env: PYTHON="3.6"

    - os: osx
      env: PYTHON="3.5"

    - os: osx
      env: PYTHON="3.6"

# Install packages
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda update -q --all
    - conda config --append channels conda-forge
    - conda config --append channels cantera
    - conda config --append channels pr-omethe-us
    - if [[ -z "$TRAVIS_TAG" ]]; then
        sed -i -e "s/\${PYTHON}/"${PYTHON}"/" test-environment.yaml;
        conda env create -qf test-environment.yaml;
        conda activate py${PYTHON};
      else
        if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
          conda env update -qn base -f build-environment.yaml;
        fi
      fi
      # Useful for debugging any issues with conda
    - conda info -a
    - conda list

# command to run tests
script:
  - set -e
  - if [[ -z "$TRAVIS_TAG" ]]; then
      pytest -vv --cov=./;
      if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
        git checkout -- test-environment.yaml;
        conda install -q sphinx doctr;
        python setup.py install;
        cd docs;
        make html SPHINXOPTS="-W";
        cd ..;
        doctr deploy .;
      fi
    else
      conda build conda.recipe --python=${PYTHON};
      anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/*/pyteck*.tar.bz2;
    fi
  - set +e

after_success:
  - if [[ -z "$TRAVIS_TAG" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

#before_deploy:
#  - conda install pandoc
#  - pip install pypandoc

deploy:
  provider: pypi
  user: kyleniemeyer
  password:
    secure: "vaCCwVyZ8m+PDWub0kpPWYwwAUrtgnFQxU9qKc6VwIp3cCtYyEAZjTbAUzBfc/DsqmpCoLI62hYrQWqq0PwFfs4/1Ho+ppJuuiPvcIs0Syh8iv37YKnQG5Yjc9OjEGOY3ZScIUz57X67dst8HBiNHZnovwh5yxoGCTYrP0HdPlQbMkU6byzpXJ/+gzZaRiXXCPElEMf7HRuOZCkoDUIxypcBAvRHjyqI5TLecfkZBllkA3MFfEMT2mDurU4fmSsS7ndcKONaW9OKWSpSEItGle1Yq68qLN3xJIDSVfWg+vAUANuNAZJwo3CyfwPdxfWq4zth9+fY56ZJg3rz2QhC4kVJIOyNfyHyLdKXCQpCg2A0zcTMItnHafKm8eN2IPKNkO+HN1mpE6+G0UTnGfQtsA3FWQvedvA/WH5f226JJ1RNlJAsMDpf08WK7tTtc4rQ0Rm9TtKiblcZ+AxQMyZCdO3UxKCzqpusZmueIbr4koPFczaQYDsldWihboWp6ToAymI1XwcsSQTQTTcqGqt5ADuI9Ae0egWqpsAe72aiTYUR/FrIXD2ylSQl0E3UobjkYl+5kT4pJtF3TknJqN4VZDAbRP1IxPGcpNXLuZXekLpNaaDxJFepAnytWtIGd/W2vt+Afv5vt5VvGLFS56uuxOkLlIFebw0NfXnT1citLLM="
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux" && $PYTHON == "3.6"
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
