name: test-environment
channels:
- defaults
- conda-forge
- cantera
- pr-omethe-us
dependencies:
  - numpy>=1.13.1
  - scipy>=1.0.0
  - pyyaml>=3.12
  - pytest>=3.0.1
  - pytest-cov>=2.3.1
  - python=${PYTHON}
  - pint>=0.7.2
  - pytables
  - cantera>=2.3.0
  - pyked>=0.3.0
