{% set data = load_setup_py_data() %}

package:
  name: pyteck
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python
    - pyyaml >=3.12,<4.0
    - numpy >=1.13.1
    - scipy >=1.0.0
    - pint >=0.7.2,<0.9
    - pytables
    - cantera >=2.3.0
    - pyked >=0.4.1

test:
  imports:
    - pyked
    - cantera

  requires:
    - pytest >=3.0.1
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs pyteck

about:
  home: data['url']
  license: MIT
  license_file: LICENSE
  license_family: MIT

  summary: data['description']
  description: data['long_description']
  doc_url: https://kyleniemeyer.github.io/PyTeCK
  dev_url: data['url']
